<nav>
    <ul>
	<li>Inicio</li>
        <li>Problemas</li>
	<li>Estadisticas</li>
    </ul>
	<ul>
		<li>Inicio</li>
		<li>Problemas</li>
		<li>Estadisticas</li>
                <li>Login</li>
                <li>descargas</li>
	</ul>
</nav>